services:
  cache:
    container_name: redis-
    image: redis
    restart: always
    ports:
      - '6378:6378'
    command: [redis-server]
    environment:
      - REDIS_PASSWORD=ada_1
      - USER=ada
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - overcommit_memory=1
      - maxmemory=1gb
    volumes:
      - ./cache:/var/lib/redis/data
